/*
envtool manages environments and github projects
within a genv environment.
The tools will be installed for each genv environment
It is best to use the tools within a genv environment
for maximum control.

This file was generated by cobra and is distributed
under the Apache-2 license which is compatible with
the BSD-2-clause license this code is under
*/
package main

import "github.com/nishakm/genv/envtool/cmd"

func main() {
	cmd.Execute()
}
